spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres  # ← DBのURL。作成したDB名を指定する。（デフォルトのDBはpostgres）
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver  # JDBCドライバのクラス名

  sql:
    init:
      mode: always  # ← これを設定すると、起動時に毎回 schema.sql → data.sql が自動的に実行される。